name: my-dev-branche workflow
on:
  push:
    branches:
      - main
      - dev
jobs:
  dev-actions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Say Hello
        run: echo "Hello from the dev branch! ðŸŽ‰"

      - name: List files
        run: ls -la 
        
      - name: Update packages
        run: sudo apt update

      - name: Install Apache
        run: sudo apt install apache2 -y

      - name: Start Apache service
        run: |
          sudo systemctl start apache2
          sudo systemctl enable apache2

      - name: Check Apache status
        run: sudo systemctl status apache2

      - name: Show Runner IP
        run: curl ifconfig.me

      - name: Test HTTP connection locally
        run: curl http://localhost
