name: my-dev-branche workflow
on:
  push:
    branches:
      - dev
jobs:
  dev-actions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Say Hello
        run: echo "Hello from the dev branch! ðŸŽ‰"

      - name: List files
        run: ls -la
      - name: check HTTP connection to my ubuntu machine
        run: |
          echo "This is the runner's IP:"
          curl ifconfig.me
