name: My First GithubActions Workflow
on: 
  push:
    branches: 
      - main
      - dev
jobs:
  job-example:
    runs-on: ubuntu-latest
    steps: 
      - name: welcome message
        run: echo "Welcome to my first githubActions Workflow!"

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: list repo file
        run: ls -la
      - name: Simple Ping
        uses: MatiasG19/ping@1.0.2
        with:
          url: https://www.google.com
    
          
