name: My First GithubActions Workflow
on: 
  push:
    branches: 
      - main
      - dev
jobs:
  job-example:
    runs-on: ubuntu-latest
    steps: 
      - name: welcome message
        run: echo "wWelcome to my first github actions Workflow!"

      - name: Checkout
        uses: actions/checkout@v6.0.2

        - name: list repo file
          run: ls -la
